name: ml_dart
description: A comprehensive ML ecosystem for Dart.
version: 1.0.0
repository: https://github.com/kiddo4/dart_ml.git

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  image: ^4.0.15
  csv: ^6.0.0
  dio: ^5.7.0
  mockito: ^5.4.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
